### ISSUE TITLE
How to call setpoint

### ISSUE THREAD

**Issue by tumsel** [martenjacobs/py-otgw-mqtt#10]
Hi Marten,
Im using your tool in home assistant and all the data is shown on the website. I get the data with (sensors):
`- platform: mqtt
    state_topic: "value/otgw/outside_temperature"
    name: "Outside temperature"
    unit_of_measurement: '°C'`
and can set some data in climate
`- platform: mqtt
    state_topic: "value/otgw/outside_temperature"
    name: "Central Heating Outside Temperature"
    unit_of_measurement: '°C'`
Is there a documentation for the declaration of how to set other values like
set/otgw/hot_water/enable
?
I think in  OTGW are some other values that can be changed. Can I do it with your tool?

**Comment by tumsel** [comment]
Hi Marten, 
Iḿ missing some possibilities for setpoint change in you list, i.e "Max. central heating water setpoint" and "Domestic hot water setpoint". I can change this values with the OTMonitor successfully. Is that possible with your tool, too?

I think your parsing for "dhw_temperature" is not working, because I dont geht imports, although there are data.

**Comment by martenjacobs** [comment]
I don't fully understand what you mean, but you should be able use these topics to control your system:

# Temperatures
These all expect a payload in the format 12.3 (decimal dot) in degrees Celsius
- set/otgw/room_setpoint/temporary
- set/otgw/room_setpoint/constant
- set/otgw/outside_temperature
- set/otgw/hot_water/temperature

# Enable/disable functions
These expect a payload with a truthy or falsey value ('True', 'true', '1', 'y', 'yes', 'False', 'false', '0', 'n', 'no')
- set/otgw/hot_water/enable
- set/otgw/central_heating/enable

I just noticed there are some more messages that are supported by the OTGW. I'm guessing these are the ones you're talking about (CS, MM, AA, DA, among others). I may add them in the future when I have the time. I'm also open to pull requests.

**Comment by tumsel** [comment]
Thanks a lot. I'm missing the possibility to change the setpoint of max CH temperature to control my CH. So I'll try a pull request. Hopefully it works; i've naver done this
