### ISSUE TITLE
serial_for_url support

### ISSUE THREAD

**Issue by fuecy** [martenjacobs/py-otgw-mqtt#12]
In opentherm_serial.py i replaced serial.Serial with serial.serial_for_url to suport "socket://<ip>" for my opentherm with NodeMCU wifi. Iam running this in a docker container and it works awesome.
Maybe you can consider taking this in your branch

**Comment by martenjacobs** [comment]
That sounds interesting, please submit a pull request if you'd like me to merge your code.
