### ISSUE TITLE
what about TCP

### ISSUE THREAD

**Issue by ppontre** [martenjacobs/py-otgw-mqtt#18]
Hello there, 
any news about TCP implementation ?
I've got an OTGW with nodeMCU and ser2net, running OtMonitor.
I could help in debug....

**Comment by martenjacobs** [comment]
Hi ppontre,

I've just added [a message](https://github.com/martenjacobs/py-otgw-mqtt#this-package-is-not-actively-maintained) explaining the fact that I'm not actively maintaining this package anymore. This means I'll not be adding features. There are some forks of this repository that include TCP support and the [tcp branch](https://github.com/martenjacobs/py-otgw-mqtt/tree/tcp) of this repo may work as well. If you need general help with your OTGW, a good source is [the OTGW forum on domoticaforum.eu](https://www.domoticaforum.eu/viewforum.php?f=75).

**Comment by ppontre** [comment]
Thanks a lot for yr info…..
Regards
Paolo


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

________________________________
Da: Marten Jacobs <notifications@github.com>
Inviato: Wednesday, May 22, 2019 8:54:37 PM
A: martenjacobs/py-otgw-mqtt
Cc: ppontre; Author
Oggetto: Re: [martenjacobs/py-otgw-mqtt] what about TCP (#18)


Hi ppontre,

I've just added a message<https://github.com/martenjacobs/py-otgw-mqtt#this-package-is-not-actively-maintained> explaining the fact that I'm not actively maintaining this package anymore. This means I'll not be adding features. There are some forks of this repository that include TCP support and the tcp branch<https://github.com/martenjacobs/py-otgw-mqtt/tree/tcp> of this repo may work as well. If you need general help with your OTGW, a good source is the OTGW forum on domoticaforum.eu<https://www.domoticaforum.eu/viewforum.php?f=75>.
