### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by HenkSnavel** [martenjacobs/py-otgw-mqtt#4]
I cant get the bridge to work.
-- Logs begin at Thu 2018-03-22 22:35:28 CET. --
Mar 22 22:40:04 xtraapi python[1362]:     code = loader.get_code(mod_name)
Mar 22 22:40:04 xtraapi python[1362]:   File "/usr/lib/python2.7/pkgutil.py", line 283, in get_code
Mar 22 22:40:04 xtraapi python[1362]:     self.code = compile(source, self.filename, 'exec')
Mar 22 22:40:04 xtraapi python[1362]:   File "/usr/lib/py-otgw-mqtt/__main__.py", line 70
Mar 22 22:40:04 xtraapi python[1362]:     lambda _ :"HW={}".format('1' if _ in true_values else '0'),
Mar 22 22:40:04 xtraapi python[1362]:          ^
Mar 22 22:40:04 xtraapi python[1362]: SyntaxError: invalid syntax
Mar 22 22:40:04 xtraapi systemd[1]: py-otgw-mqtt.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 22:40:04 xtraapi systemd[1]: py-otgw-mqtt.service: Unit entered failed state.
Mar 22 22:40:04 xtraapi systemd[1]: py-otgw-mqtt.service: Failed with result 'exit-code'.

`

**Comment by martenjacobs** [comment]
You're right. I see my last commit introduced a syntax error. Major oops on my part. Could you please try again?

**Comment by martenjacobs** [comment]
Closing this. I’m pretty sure it’s solved and no response from OP
