### ISSUE TITLE
You're right. I see my last commit introduced a syntax error. Major oops on my part. Could you please try again?

### ISSUE THREAD

**Issue by tumsel** [martenjacobs/py-otgw-mqtt#9]
Hi Marten,
thanks a lot for your wonderful tool. I installed it as you described but i think, i dont have enough knowledge and information. Can you tell me where I can start for deeper information? When I started the tool I got this error message:
Jan 02 19:48:58 raspberrypi systemd[1]: py-otgw-mqtt.service: Main process exited, code=exited, status=1/FAILURE
Jan 02 19:48:58 raspberrypi systemd[1]: py-otgw-mqtt.service: Unit entered failed state.
Jan 02 19:48:58 raspberrypi systemd[1]: py-otgw-mqtt.service: Failed with result 'exit-code'.
Jan 02 20:47:26 raspberrypi systemd[1]: Started Python OTGW MQTT bridge.
Jan 02 20:47:27 raspberrypi python[2963]: INFO:__main__:Initializing MQTT
Jan 02 20:47:27 raspberrypi python[2963]: INFO:__main__:Initializing OTGW
Jan 02 20:47:27 raspberrypi python[2963]: INFO:__main__:Running
Jan 02 20:47:27 raspberrypi python[2963]: INFO:__main__:Connected with result code 0

**Comment by martenjacobs** [comment]
The last few lines seem to suggest the service is running properly. Can you please check if it is? It’s possible systemd started it up too early and then retried later

**Comment by tumsel** [comment]
I dont know exactly what I have to check. Could you pls. explain? I startet the py-otgw-mqtt.service manually via a restart. So it should be the latest startet service. 
In my understanding your tool directly communicates with the serial port(USB) with the otgw (and not with the OTmonitor). So the OTmonitor is not running. Hopefully this is right. What do you mean by saying: "started it up too early"? When is "too early"? What should happen before that?
Do you know a good site to get a deeper understanding of OTGW an MQtt (working together)?

**Comment by tumsel** [comment]
Now it works fine. Thanks for your support!
